INSERT INTO gear_catalog (manufacturer, model, category) VALUES
('Beal','Hold Up Chest Ascender','ascender'),
('Beal','Air Hook Large','carabiner'),
('Beal','Air Smith 3-Matic','carabiner'),
('Beal','Be Quick','carabiner'),
('Beal','Be Safe','carabiner'),
('Beal','O''Light 3-Matic','carabiner'),
('Beal','Air Stop','descender'),
('Beal','Air Top','harness'),
('Beal','Dragon','harness'),
('Beal','Dragon Top','harness'),
('Beal','Evacuation Triangle','harness'),
('Beal','Hero Pro','harness'),
('Beal','Hero Sit','harness'),
('Beal','Offshore','harness'),
('Beal','Shaolin','harness'),
('Beal','Styxbelt','harness'),
('Beal','Styxfast','harness'),
('Beal','Hard Rock Helmet','helmet'),
('Beal','Dynaclip','lanyard'),
('Beal','Dynapro 8','lanyard'),
('Beal','Dynapro Air Hook','lanyard'),
('Beal','Dynapro Air V Hook','lanyard'),
('Beal','Ergo Lanyard','lanyard'),
('Beal','Mobile Lanyard','lanyard'),
('Beal','Air Leash','other'),
('Beal','Edge Guard','other'),
('Beal','Escaper','other'),
('Beal','Genius Tool Bucket','other'),
('Beal','Glass-Bucket','other'),
('Beal','Hot Protector','other'),
('Beal','Long Tool Bucket','other'),
('Beal','Monitor Mobile Fall Arrester','other'),
('Beal','Pinch','other'),
('Beal','Super Leash','other'),
('Beal','Workseat','other'),
('Beal','Access Unicore 10.5mm','rope'),
('Beal','Aider Tactic 11mm','rope'),
('Beal','Antipodes 11.5mm','rope'),
('Beal','Australis','rope'),
('Beal','Baobab','rope'),
('Beal','Berlin 9.8 Unicore','rope'),
('Beal','Contract','rope'),
('Beal','Hotline 11mm','rope'),
('Beal','Industrie 10.5mm','rope'),
('Beal','Industrie 11mm','rope'),
('Beal','Pro Water 11mm','rope'),
('Beal','Raider Tactic 11mm','rope'),
('Beal','Rescue VLS','rope'),
('BlueWater','Assaultline','rope'),
('BlueWater','BlueWater II Plus','rope'),
('BlueWater','Canyon Pro','rope'),
('BlueWater','Canyon Pro DS','rope'),
('BlueWater','Canyonator 9.2mm','rope'),
('BlueWater','DGR','rope'),
('BlueWater','Lightning Pro','rope'),
('BlueWater','Pro-G Static','rope'),
('BlueWater','Safeline','rope'),
('BlueWater','Spec-Static','rope'),
('BlueWater','NFPA Sewn Eye Sling','sling'),
('CMC','ProSteel Carabiner','carabiner'),
('CMC','ProTech Carabiner','carabiner'),
('CMC','SwivaBiner','carabiner'),
('CMC','CLUTCH','descender'),
('CMC','LEVR','descender'),
('CMC','MPD','descender'),
('CMC','ProSeries Rescue 8','descender'),
('CMC','ATOM Access','harness'),
('CMC','ATOM Access Plus','harness'),
('CMC','ATOM Chest Harness','harness'),
('CMC','ATOM Global','harness'),
('CMC','ATOM Global Quick','harness'),
('CMC','ATOM Rescue','harness'),
('CMC','Fulcrum Escape Belt','harness'),
('CMC','Outback Convertible','harness'),
('CMC','Dynamic Bullnose Lanyard','lanyard'),
('CMC','Dynamic I-Lanyard','lanyard'),
('CMC','BOOST Foot Loop','other'),
('CMC','CAPTO','other'),
('CMC','Pick-Off Strap','other'),
('CMC','SQUID','other'),
('CMC','AZTEK ProSeries','pulley'),
('CMC','CSR2 Pulley','pulley'),
('CMC','ProSwivel Pulley','pulley'),
('CMC','SWIVO','pulley'),
('CMC','Static-Pro Lifeline','rope'),
('CMC','T95','rope'),
('CMC','Compact Sling','sling'),
('CMC','SL Anchor Strap','sling'),
('CMC','Variable Anchor Strap','sling'),
('DBI-SALA','Saflok Carabiner','carabiner'),
('DBI-SALA','Rollgliss Bucket Truck Rescue','descender'),
('DBI-SALA','Rollgliss R250','descender'),
('DBI-SALA','Rollgliss R350','descender'),
('DBI-SALA','Delta','harness'),
('DBI-SALA','ExoFit NEX','harness'),
('DBI-SALA','ExoFit NEX Rope Access Rescue','harness'),
('DBI-SALA','ExoFit X100','harness'),
('DBI-SALA','ExoFit X200','harness'),
('DBI-SALA','ExoFit X300','harness'),
('DBI-SALA','Nano-Lok','lanyard'),
('DBI-SALA','Nano-Lok Edge','lanyard'),
('DBI-SALA','Sealed-Blok','lanyard'),
('DBI-SALA','Shockwave 2','lanyard'),
('DBI-SALA','Talon','lanyard'),
('DBI-SALA','Ultra-Lok','lanyard'),
('DBI-SALA','Lad-Saf X3 Cable Sleeve','other'),
('DBI-SALA','SecuraSpan Horizontal Lifeline','other'),
('DMM','Aero','carabiner'),
('DMM','Alpha Steel','carabiner'),
('DMM','Belay Master 2','carabiner'),
('DMM','Boa','carabiner'),
('DMM','Boa HMS Locksafe','carabiner'),
('DMM','Ceros','carabiner'),
('DMM','Director','carabiner'),
('DMM','Equal D Steel','carabiner'),
('DMM','Klettersteig','carabiner'),
('DMM','Mamba Screwgate','carabiner'),
('DMM','Oval Steel','carabiner'),
('DMM','PerfectO','carabiner'),
('DMM','Phantom','carabiner'),
('DMM','Revolver','carabiner'),
('DMM','Revolver Rig','carabiner'),
('DMM','Revolver Wire Gate','carabiner'),
('DMM','Rhino HMS','carabiner'),
('DMM','Rhino HMS Locksafe','carabiner'),
('DMM','Sentinel','carabiner'),
('DMM','Shadow HMS','carabiner'),
('DMM','Shadow Locking','carabiner'),
('DMM','Spectre 2','carabiner'),
('DMM','Ultra D','carabiner'),
('DMM','Ultra O','carabiner'),
('DMM','XSRE','carabiner'),
('DMM','Pivot','descender'),
('DMM','Captain','harness'),
('DMM','Kinisi','harness'),
('DMM','Kinisi Max','harness'),
('DMM','Fidus Thimble Loop','lanyard'),
('DMM','Nomad Lanyard','lanyard'),
('DMM','Axis Swivel','other'),
('DMM','Bat Plate','other'),
('DMM','Compact Shackle','other'),
('DMM','Director Swivel Boss','other'),
('DMM','Director Yoke','other'),
('DMM','Focus','other'),
('DMM','Mega Vault','other'),
('DMM','Micro Vault','other'),
('DMM','Porter Bag','other'),
('DMM','Rigging Hub','other'),
('DMM','Tool Bag','other'),
('DMM','Vault','other'),
('DMM','Buddy','pulley'),
('DMM','Hitch Climber Eccentric','pulley'),
('DMM','Hitch Climber V2','pulley'),
('DMM','Impact Block Small','pulley'),
('DMM','Pinto 2','pulley'),
('DMM','Pinto Rig','pulley'),
('DMM','Propel','pulley'),
('DMM','Rigger Becket','pulley'),
('DMM','Triple Attachment Pulley','pulley'),
('DMM','Dynatec Sling','sling'),
('DMM','Tech Sling','sling'),
('Edelrid','Foot Cruiser','ascender'),
('Edelrid','Tree Cruiser','ascender'),
('Edelrid','Axiom Pulley Carabiner','carabiner'),
('Edelrid','DSG Triton','carabiner'),
('Edelrid','HMS Bulletproof','carabiner'),
('Edelrid','HMS Magnum Triple','carabiner'),
('Edelrid','HMS Strike Screw','carabiner'),
('Edelrid','HMS Strike Slider','carabiner'),
('Edelrid','HMS Strike Triple','carabiner'),
('Edelrid','Oval Power','carabiner'),
('Edelrid','Oval Power 2500 Screw','carabiner'),
('Edelrid','Oval Power 2500 Triple','carabiner'),
('Edelrid','Permalock','carabiner'),
('Edelrid','Pure Screw','carabiner'),
('Edelrid','Pure Slider','carabiner'),
('Edelrid','Pure Triple','carabiner'),
('Edelrid','Safelock','carabiner'),
('Edelrid','Eddy','descender'),
('Edelrid','Hannibal','descender'),
('Edelrid','Mega Jul','descender'),
('Edelrid','Megawatt','descender'),
('Edelrid','Nano Jul','descender'),
('Edelrid','Flex Lite','harness'),
('Edelrid','Flex Pro','harness'),
('Edelrid','Flex Pro Plus','harness'),
('Edelrid','Helios','harness'),
('Edelrid','Treeraptor','harness'),
('Edelrid','Treerex Bungee Chest','harness'),
('Edelrid','Treerex II','harness'),
('Edelrid','Vector Chest X','harness'),
('Edelrid','Vector Waist Belt','harness'),
('Edelrid','Vertic Triple Lock','harness'),
('Edelrid','Vertic Triple Lock Black','harness'),
('Edelrid','Zodiac 3R','helmet'),
('Edelrid','Zodiac Helmet','helmet'),
('Edelrid','Cable Kit','lanyard'),
('Edelrid','Ombilix Adjust','lanyard'),
('Edelrid','Switch Adjust','lanyard'),
('Edelrid','Switch Double Adjust','lanyard'),
('Edelrid','Switch Pro Double Adjust','lanyard'),
('Edelrid','Fuse','other'),
('Edelrid','Ohm II','other'),
('Edelrid','Professional Rope Protector','other'),
('Edelrid','Talon Tree Crampon','other'),
('Edelrid','Rail Double','pulley'),
('Edelrid','Spoc','pulley'),
('Edelrid','Performance Static 11mm','rope'),
('Edelrid','Rap Line II','rope'),
('Edelrid','Super Static','rope'),
('Edelrid','Swift 48 Pro Dry 8.9mm','rope'),
('Falltech','Twist Lock Carabiner','carabiner'),
('Falltech','Carbon FT-One Fit Tower','harness'),
('Falltech','Carbon FT-One Tower','harness'),
('Falltech','ComforTech 6D Tower','harness'),
('Falltech','Contractor Universal','harness'),
('Falltech','FlowTech LTE','harness'),
('Falltech','FT-Weld','harness'),
('Falltech','Journeyman Flex Steel','harness'),
('Falltech','Roughneck','harness'),
('Falltech','Tradesman Plus','harness'),
('Falltech','DuraTech SRD','lanyard'),
('Falltech','ViewPack Shock-Absorbing Lanyard','lanyard'),
('Falltech','Hinged Trailing Rope Grab','other'),
('Falltech','Manual Rope Grab','other'),
('Falltech','Cable Sling Anchor','sling'),
('Falltech','Web Pass-Through Anchor Sling','sling'),
('Guardian Fall Protection','B7-Comfort','harness'),
('Guardian Fall Protection','Defender','harness'),
('Guardian Fall Protection','Series 1','harness'),
('Guardian Fall Protection','Series 3','harness'),
('Guardian Fall Protection','Series 5','harness'),
('Guardian Fall Protection','CR3-Edge SRL','lanyard'),
('Guardian Fall Protection','Diablo SRL','lanyard'),
('Guardian Fall Protection','Halo SRL','lanyard'),
('Guardian Fall Protection','Internal Shock Lanyard 11200','lanyard'),
('Guardian Fall Protection','A5 Concrete Anchor','other'),
('Heightec','Compact Basic Ascender','ascender'),
('Heightec','Pulsar Ascender','ascender'),
('Heightec','Sync Chest Ascender','ascender'),
('Heightec','Alloy Karabiner Offset Tri-Act','carabiner'),
('Heightec','Alloy Scaffold Hook','carabiner'),
('Heightec','Alloy Scaffold Hook Rescue','carabiner'),
('Heightec','ALTO Alloy Oval Screwgate','carabiner'),
('Heightec','ALTO Alloy Oval Tri-Act','carabiner'),
('Heightec','ALTUS Aluminium D Screwgate','carabiner'),
('Heightec','ALTUS Aluminium Tri-Act','carabiner'),
('Heightec','CONTRACT Steel Oval Screwgate','carabiner'),
('Heightec','Delta Screwlink','carabiner'),
('Heightec','FastClip','carabiner'),
('Heightec','Steel D Twistlock Captive','carabiner'),
('Heightec','Steel HMS Screwgate 45kN','carabiner'),
('Heightec','Steel HMS Twist Lock 45kN','carabiner'),
('Heightec','Micron Self Evacuation Descender','descender'),
('Heightec','Powerlock','descender'),
('Heightec','Prism Descender','descender'),
('Heightec','Quadra Rescue Device','descender'),
('Heightec','Rotor Automatic Rescue Descender','descender'),
('Heightec','Vector Descender','descender'),
('Heightec','Apex Modular Harness','harness'),
('Heightec','Aura Modular System','harness'),
('Heightec','Casualty Harness','harness'),
('Heightec','CORONA','harness'),
('Heightec','ECLIPSE','harness'),
('Heightec','Extol Rope Access Harness','harness'),
('Heightec','MATRIX','harness'),
('Heightec','Neon Rigger''s Harness','harness'),
('Heightec','NEXUS','harness'),
('Heightec','Phoenix','harness'),
('Heightec','Workseat','harness'),
('Heightec','Duon','helmet'),
('Heightec','Duon Air','helmet'),
('Heightec','Elite Twin Lanyard','lanyard'),
('Heightec','FLEXOR Elasticated Twin Lanyard','lanyard'),
('Heightec','Piranha Adjustable Lanyard','lanyard'),
('Heightec','TENSOR Twin Lanyard','lanyard'),
('Heightec','4 Step Footloop','other'),
('Heightec','Gratemate Rope Protector','other'),
('Heightec','Hurricane Hauling Device','other'),
('Heightec','Kari Transport Bag','other'),
('Heightec','LASER Temporary Horizontal Anchor Line','other'),
('Heightec','MANTLE Canvas Rope Protector','other'),
('Heightec','QUADPOD Portable Anchor','other'),
('Heightec','Quantum Back-up Device','other'),
('Heightec','RescuePack WTG','other'),
('Heightec','Rigger''s Tower Climbing Kit','other'),
('Heightec','Sentinel Rope Protector','other'),
('Heightec','Suspension Relief Footloop','other'),
('Heightec','Towerlatch','other'),
('Heightec','Xtendr Rescue Pole','other'),
('Heightec','Alloy Pulley 2cm','pulley'),
('Heightec','Alloy Rescue Pulley 5cm','pulley'),
('Heightec','CYCLONE Hauling Pulley','pulley'),
('Heightec','HEXAN 6:1 Pulley System','pulley'),
('Heightec','Stainless Steel Pulley 5cm','pulley'),
('Heightec','Swing Cheek Pulley','pulley'),
('Heightec','Vantage Rescue Pulley','pulley'),
('Heightec','6mm Accessory Cord','rope'),
('Heightec','ENERGIS Dynamic Rope 10mm','rope'),
('Heightec','Tectra 11mm Low Stretch','rope'),
('Heightec','Protected Sewn Nylon Sling','sling'),
('Heightec','Sewn Nylon Sling','sling'),
('ISC Wales','RP210 Professional Hand Ascender Left','ascender'),
('ISC Wales','RP220 Professional Hand Ascender Right','ascender'),
('ISC Wales','RP227 STRYDER Foot Ascender','ascender'),
('ISC Wales','RP229 Chest Ascender','ascender'),
('ISC Wales','RP240 Ultrasafe Hand Ascender','ascender'),
('ISC Wales','Big Dan SuperSafe','carabiner'),
('ISC Wales','Iron Wizard','carabiner'),
('ISC Wales','KH200 Stainless D Shape','carabiner'),
('ISC Wales','KH204 HMS Karabiner','carabiner'),
('ISC Wales','KH212 Steel HMS','carabiner'),
('ISC Wales','KH214 Mini HMS','carabiner'),
('ISC Wales','KH215 Link','carabiner'),
('ISC Wales','KH218 Aluminium Wizard','carabiner'),
('ISC Wales','KH219 Stainless Iron Wizard','carabiner'),
('ISC Wales','KH221 Aluminium Offset Oval','carabiner'),
('ISC Wales','KH250 Stainless Twister','carabiner'),
('ISC Wales','KH255 Twister','carabiner'),
('ISC Wales','KH260 Steel Twister','carabiner'),
('ISC Wales','KH300 Captive Eye','carabiner'),
('ISC Wales','KH301 Steel Captive Eye','carabiner'),
('ISC Wales','KH307 Firemans Karabiner','carabiner'),
('ISC Wales','KH308 Stainless Offset D','carabiner'),
('ISC Wales','KH407 Scaffold Hook','carabiner'),
('ISC Wales','KH415 Iron Wizard Large','carabiner'),
('ISC Wales','KH451 Mongoose','carabiner'),
('ISC Wales','KH452 Gecko','carabiner'),
('ISC Wales','KH453 Gator','carabiner'),
('ISC Wales','KL100 Accessory Karabiner','carabiner'),
('ISC Wales','KL120 Compact Oval','carabiner'),
('ISC Wales','KL121 Aluminium Oval','carabiner'),
('ISC Wales','KL200 Offset D Keylock','carabiner'),
('ISC Wales','KL202 Klettersteig Keylock','carabiner'),
('ISC Wales','KL216 Offset Karabiner','carabiner'),
('ISC Wales','KL308 D Shape Keylock','carabiner'),
('ISC Wales','KL311 Steel Oval Keylock','carabiner'),
('ISC Wales','KL321 Offset Oval Keylock','carabiner'),
('ISC Wales','SH907 Triple-Action Snaphook','carabiner'),
('ISC Wales','Triple Action Snaphook','carabiner'),
('ISC Wales','UltraLink Large','carabiner'),
('ISC Wales','UltraLink Small','carabiner'),
('ISC Wales','D1PRO Escape','descender'),
('ISC Wales','D1PRO Tactical','descender'),
('ISC Wales','D2 Personal Escape','descender'),
('ISC Wales','D4 Work/Rescue Descender','descender'),
('ISC Wales','D4PRO Work/Rescue Descender','descender'),
('ISC Wales','D5 Descender','descender'),
('ISC Wales','D5PRO Work/Rescue Descender','descender'),
('ISC Wales','Rescue Figure 8','descender'),
('ISC Wales','Sar A-B Descender','descender'),
('ISC Wales','Singing Tree Rope Wrench RP280','descender'),
('ISC Wales','DW200 A-Frame Deadweight Anchor','other'),
('ISC Wales','Edge Roller ER100','other'),
('ISC Wales','GG301 Medium Pre-Cast Anchor','other'),
('ISC Wales','HaulerBiner Compact Rescue Kit','other'),
('ISC Wales','NESSIE Lanyard Clip','other'),
('ISC Wales','REFLEX Mechanical Hitch','other'),
('ISC Wales','Rocker Ropegrab RP500','other'),
('ISC Wales','RP300 Small Rigging Plate','other'),
('ISC Wales','RP310 Medium Rigging Plate','other'),
('ISC Wales','SmartSnap','other'),
('ISC Wales','Squirrel Tether','other'),
('ISC Wales','Steel Ring 70kN','other'),
('ISC Wales','UltraLink','other'),
('ISC Wales','200 Series Rigging Pulley','pulley'),
('ISC Wales','Eiger Pulley','pulley'),
('ISC Wales','Prussik Pulley','pulley'),
('ISC Wales','R-ALF Locking Pulley','pulley'),
('ISC Wales','Rope Wrench Pulley RP281','pulley'),
('ISC Wales','RP048 Compact Rigging Pulley','pulley'),
('ISC Wales','RP051 Small Forged Pulley','pulley'),
('ISC Wales','RP054 Medium Forged Pulley','pulley'),
('ISC Wales','RP248 200-Series Compact Rigging Pulley','pulley'),
('ISC Wales','RP251 200-Series Small Rigging Pulley','pulley'),
('ISC Wales','RP255 200-Series Medium Rigging Pulley','pulley'),
('ISC Wales','RP257 200-Series Large Rigging Pulley','pulley'),
('ISC Wales','ZipSpeed Tandem','pulley'),
('ISC Wales','WS100 Wire Anchor Strop','sling'),
('Kong','Duck','ascender'),
('Kong','Futura Body','ascender'),
('Kong','Futura Foot','ascender'),
('Kong','Futura Hand','ascender'),
('Kong','Lift','ascender'),
('Kong','Ninja Foot','ascender'),
('Kong','Kanguro','carabiner'),
('Kong','Ovalone','carabiner'),
('Kong','Trapper','carabiner'),
('Kong','X-Large','carabiner'),
('Kong','Hydrobot','descender'),
('Kong','Indy Evo','descender'),
('Kong','Oka','descender'),
('Kong','Sierra Duo','harness'),
('Kong','Stark','harness'),
('Kong','Target Canyon','harness'),
('Kong','Target Cave','harness'),
('Kong','Top Tree','harness'),
('Kong','Tower','harness'),
('Kong','Mouse Work','helmet'),
('Kong','Plaster Helmet','helmet'),
('Kong','Scarab','helmet'),
('Kong','Slyde','lanyard'),
('Kong','Back-Up','other'),
('Kong','Modular Pulley','pulley'),
('Kong','Robot Pulley','pulley'),
('Kong','Semi-Static 10.5mm','rope'),
('Kong','Static 11mm','rope'),
('Miller','AirCore','harness'),
('Miller','DuraFlex','harness'),
('Miller','H500 Construction Comfort','harness'),
('Miller','H700 Construction Comfort','harness'),
('Miller','H700 Industry Comfort','harness'),
('Miller','Revolution DualTech','harness'),
('Miller','Titan','harness'),
('Miller','Falcon+ Cable Retractable','lanyard'),
('Miller','HP Shock-Absorbing Lanyard','lanyard'),
('Miller','Manyard II','lanyard'),
('Miller','TurboLite+','lanyard'),
('Miller','ManHandler Winch','other'),
('Miller','Vi-Go Ladder Climbing System','other'),
('MSA','EVOTECH','harness'),
('MSA','EVOTECH Arc Flash','harness'),
('MSA','Gravity','harness'),
('MSA','Latchways PRD','harness'),
('MSA','Workman','harness'),
('MSA','Comfo-Cap','helmet'),
('MSA','Skullgard','helmet'),
('MSA','V-Gard','helmet'),
('MSA','V-Gard H1','helmet'),
('MSA','V-Gard H1 Pro','helmet'),
('MSA','V-EDGE SRL','lanyard'),
('MSA','V-Series Shock Absorbing Lanyard','lanyard'),
('MSA','V-SHOCK Personal Fall Limiter','lanyard'),
('MSA','SureClimb Vertical Lifeline','other'),
('Petzl','Ascension','ascender'),
('Petzl','Ascentree','ascender'),
('Petzl','Basic','ascender'),
('Petzl','Croll L','ascender'),
('Petzl','Croll S','ascender'),
('Petzl','Knee Ascent Cam','ascender'),
('Petzl','Knee Ascent Loop','ascender'),
('Petzl','Pantin','ascender'),
('Petzl','Tibloc','ascender'),
('Petzl','Am''D','carabiner'),
('Petzl','Attache','carabiner'),
('Petzl','Bm''D','carabiner'),
('Petzl','Freino Z','carabiner'),
('Petzl','OK','carabiner'),
('Petzl','Omni','carabiner'),
('Petzl','Oxan','carabiner'),
('Petzl','Sm''D','carabiner'),
('Petzl','Vertigo','carabiner'),
('Petzl','Vulcan','carabiner'),
('Petzl','William','carabiner'),
('Petzl','Chicane','descender'),
('Petzl','Grigri','descender'),
('Petzl','I''D Evac','descender'),
('Petzl','I''D L','descender'),
('Petzl','I''D S','descender'),
('Petzl','Maestro L','descender'),
('Petzl','Maestro S','descender'),
('Petzl','Rig','descender'),
('Petzl','Simple','descender'),
('Petzl','Stop','descender'),
('Petzl','Zigzag','descender'),
('Petzl','Zigzag Plus','descender'),
('Petzl','Astro Bod Fast','harness'),
('Petzl','Astro Sit Fast','harness'),
('Petzl','Avao Bod','harness'),
('Petzl','Avao Bod Fast','harness'),
('Petzl','Avao Sit','harness'),
('Petzl','Avao Sit Fast','harness'),
('Petzl','Falcon','harness'),
('Petzl','Falcon Ascent','harness'),
('Petzl','Falcon Mountain','harness'),
('Petzl','Newton','harness'),
('Petzl','Newton Easyfit','harness'),
('Petzl','Newton Fast Jak','harness'),
('Petzl','Sam','harness'),
('Petzl','Sequoia','harness'),
('Petzl','Sequoia SRT','harness'),
('Petzl','Top','harness'),
('Petzl','Top Croll S','harness'),
('Petzl','Volt','harness'),
('Petzl','Volt Wind','harness'),
('Petzl','Boreo','helmet'),
('Petzl','Strato','helmet'),
('Petzl','Strato Vent','helmet'),
('Petzl','Vertex','helmet'),
('Petzl','Vertex Hi-Viz','helmet'),
('Petzl','Vertex Vent','helmet'),
('Petzl','Absorbica-I','lanyard'),
('Petzl','Absorbica-Y','lanyard'),
('Petzl','Asap''Sorber','lanyard'),
('Petzl','Grillon','lanyard'),
('Petzl','Jane','lanyard'),
('Petzl','Microflip','lanyard'),
('Petzl','Progress Adjust-I','lanyard'),
('Petzl','Zillon','lanyard'),
('Petzl','ASAP','other'),
('Petzl','ASAP Lock','other'),
('Petzl','Caritool','other'),
('Petzl','Footape','other'),
('Petzl','Footcord','other'),
('Petzl','Litepod','other'),
('Petzl','Podium','other'),
('Petzl','Protec','other'),
('Petzl','Rescucender','other'),
('Petzl','Shunt','other'),
('Petzl','Toolink','other'),
('Petzl','Tooltape','other'),
('Petzl','Fixe','pulley'),
('Petzl','Micro Traxion','pulley'),
('Petzl','Minder L1','pulley'),
('Petzl','Minder S1','pulley'),
('Petzl','Mini Traxion','pulley'),
('Petzl','Pro Traxion','pulley'),
('Petzl','Rescue','pulley'),
('Petzl','Rollclip A','pulley'),
('Petzl','Rollclip Z','pulley'),
('Petzl','Spin L1','pulley'),
('Petzl','Spin L1D','pulley'),
('Petzl','Spin L2','pulley'),
('Petzl','Spin S1','pulley'),
('Petzl','Trac','pulley'),
('Petzl','Trac Plus','pulley'),
('Petzl','Axis 11mm','rope'),
('Petzl','Club 10mm','rope'),
('Petzl','Parallel 10.5mm','rope'),
('Petzl','Push 9mm','rope'),
('Petzl','Vector 12.5mm','rope'),
('Petzl','Anneau','sling'),
('Petzl','Connexion Fixe','sling'),
('Petzl','Pur''Anneau','sling'),
('PMI','Advantage Helmet','helmet'),
('PMI','Pit Viper Helmet','helmet'),
('PMI','Dura-Shield Pro Litter Bridle','lanyard'),
('PMI','Dynamic Versa Lanyard','lanyard'),
('PMI','Rope Bag Standard','other'),
('PMI','Rope Guard 24','other'),
('PMI','Dura-Shield Explorer','rope'),
('PMI','Dura-Shield Tech','rope'),
('PMI','Extreme Pro G','rope'),
('PMI','Hudson Classic Old Glory','rope'),
('PMI','Hudson Classic Professional','rope'),
('PMI','Isostatic Polyester','rope'),
('PMI','Max Wear Hudson Classic Sport','rope'),
('PMI','Patriot Vertical Lifeline','rope'),
('PMI','Pit Rope Max Wear','rope'),
('PMI','Son of Pit Rope','rope'),
('PMI','Anchor Hitch Sling','sling'),
('PMI','ANSI Anchor Sling','sling'),
('Protecta','AD111A Harness','harness'),
('Protecta','First Harness','harness'),
('Protecta','Pro Dual Leg Stretch Lanyard','lanyard'),
('Protecta','Rebel SRL','lanyard'),
('Protecta','Pro Line Horizontal Lifeline','other'),
('Rock Exotica','Pirate','carabiner'),
('Rock Exotica','rockD','carabiner'),
('Rock Exotica','rockO','carabiner'),
('Rock Exotica','rockSteel','carabiner'),
('Rock Exotica','rockX','carabiner'),
('Rock Exotica','SwivaBiner','carabiner'),
('Rock Exotica','Akimbo','descender'),
('Rock Exotica','Akimbo 2','descender'),
('Rock Exotica','DownRigger','descender'),
('Rock Exotica','MiniEight','descender'),
('Rock Exotica','Rescue Eight','descender'),
('Rock Exotica','Totem','descender'),
('Rock Exotica','Unicender','descender'),
('Rock Exotica','AZTEK Pro Kit','other'),
('Rock Exotica','Enforcer Load Cell','other'),
('Rock Exotica','rockGrab','other'),
('Rock Exotica','Transporter','other'),
('Rock Exotica','TriRig','other'),
('Rock Exotica','Vortex','other'),
('Rock Exotica','Hydra','pulley'),
('Rock Exotica','Kootenay Ultra','pulley'),
('Rock Exotica','Machined Pulley','pulley'),
('Rock Exotica','Machined Rescue Pulley','pulley'),
('Rock Exotica','Mini Machined Pulley','pulley'),
('Rock Exotica','Omni-Block 1.1','pulley'),
('Rock Exotica','Omni-Block 1.5','pulley'),
('Rock Exotica','Omni-Block 2.0','pulley'),
('Rock Exotica','Omni-Block 2.6','pulley'),
('Rock Exotica','Omni-Block SwivaBiner','pulley'),
('Singing Rock','Cam Clean','ascender'),
('Singing Rock','Lift Ascender','ascender'),
('Singing Rock','Colt Carabiner','carabiner'),
('Singing Rock','Mini Accessory Carabiner','carabiner'),
('Singing Rock','Mini D Screwgate','carabiner'),
('Singing Rock','Mini Pear Accessory','carabiner'),
('Singing Rock','Oval Steel Carabiner','carabiner'),
('Singing Rock','Oxy Carabiner','carabiner'),
('Singing Rock','Steel Triple Lock','carabiner'),
('Singing Rock','Vision','carabiner'),
('Singing Rock','Double Stop Plus','descender'),
('Singing Rock','Figure 8','descender'),
('Singing Rock','Jack Descender','descender'),
('Singing Rock','Rescue Figure 8','descender'),
('Singing Rock','Sir Descender','descender'),
('Singing Rock','Body II','harness'),
('Singing Rock','Bow','harness'),
('Singing Rock','Expert 3D Speed','harness'),
('Singing Rock','Expert 3D Standard','harness'),
('Singing Rock','Franklin Work Seat','harness'),
('Singing Rock','Garnet','harness'),
('Singing Rock','Laika Dog Rescue Harness','harness'),
('Singing Rock','Penguin','harness'),
('Singing Rock','Profi Worker 3D Speed','harness'),
('Singing Rock','Profi Worker 3D Standard','harness'),
('Singing Rock','RL Chest Work','harness'),
('Singing Rock','Sit Worker II','harness'),
('Singing Rock','Sit Worker III','harness'),
('Singing Rock','Spinel','harness'),
('Singing Rock','Technic','harness'),
('Singing Rock','Timber 3D','harness'),
('Singing Rock','Top Chest Harness','harness'),
('Singing Rock','Urban II','harness'),
('Singing Rock','Access Helmet','helmet'),
('Singing Rock','Aero Helmet','helmet'),
('Singing Rock','Flash Aero Helmet','helmet'),
('Singing Rock','Flash Helmet','helmet'),
('Singing Rock','Hex Helmet','helmet'),
('Singing Rock','Industry Helmet','helmet'),
('Singing Rock','Penta Helmet','helmet'),
('Singing Rock','Atika Rope Protector','other'),
('Singing Rock','Back Up Fall Arrester','other'),
('Singing Rock','Detachable Ring','other'),
('Singing Rock','Edge Roller','other'),
('Singing Rock','Footer II','other'),
('Singing Rock','Locker','other'),
('Singing Rock','Porter Tool Holder','other'),
('Singing Rock','Easy Lift Rescue Pulley','pulley'),
('Singing Rock','Extra Pulley','pulley'),
('Singing Rock','Mini Roll Pulley','pulley'),
('Singing Rock','Red Block','pulley'),
('Singing Rock','Small Pulley','pulley'),
('Singing Rock','Tandem Pulley','pulley'),
('Singing Rock','Route 44','rope'),
('Singing Rock','Dyneema Sling 11mm','sling'),
('Skedco','Drag-N-Lift Harness','harness'),
('Skedco','HMD Hasty Harness','harness'),
('Skedco','Half-Sked','other'),
('Skedco','Oregon Spine Splint II','other'),
('Skedco','Sked Stretcher Basic','other'),
('Skylotec','Get Up','ascender'),
('Skylotec','Quick Tree Foot Clamp','ascender'),
('Skylotec','Stand Up','ascender'),
('Skylotec','FS 110 ALU','carabiner'),
('Skylotec','FS 51 ST','carabiner'),
('Skylotec','FS 64 ST','carabiner'),
('Skylotec','FS 90 ALU','carabiner'),
('Skylotec','FS 90 ST','carabiner'),
('Skylotec','FS 90 ST ANSI','carabiner'),
('Skylotec','FS 92','carabiner'),
('Skylotec','Kobra Tri','carabiner'),
('Skylotec','OBX','carabiner'),
('Skylotec','Ovaloy Screw','carabiner'),
('Skylotec','Ovaloy Tri','carabiner'),
('Skylotec','Ovaloy Twist','carabiner'),
('Skylotec','OvalSteel Tri','carabiner'),
('Skylotec','OvalSteel TW','carabiner'),
('Skylotec','OVX','carabiner'),
('Skylotec','PassO-Tri','carabiner'),
('Skylotec','TriLock','carabiner'),
('Skylotec','Viper Steel SC','carabiner'),
('Skylotec','A-330','descender'),
('Skylotec','A-370','descender'),
('Skylotec','A-730','descender'),
('Skylotec','Lory','descender'),
('Skylotec','Lory Pro','descender'),
('Skylotec','Milan','descender'),
('Skylotec','Milan 2.0','descender'),
('Skylotec','Milan 2.0 Hub','descender'),
('Skylotec','Milan 2.0 Power','descender'),
('Skylotec','Sirius','descender'),
('Skylotec','Spark','descender'),
('Skylotec','Spark Tactical','descender'),
('Skylotec','ARG 30','harness'),
('Skylotec','CS 2','harness'),
('Skylotec','CS 4','harness'),
('Skylotec','Ignite ARB','harness'),
('Skylotec','Ignite Argon','harness'),
('Skylotec','Ignite Ion','harness'),
('Skylotec','Ignite Mounter','harness'),
('Skylotec','Ignite Neon','harness'),
('Skylotec','Ignite Proton Wind','harness'),
('Skylotec','Ignite Strato','harness'),
('Skylotec','Ignite Trion','harness'),
('Skylotec','Inceptor GRX','helmet'),
('Skylotec','Inceptor GRX High Voltage','helmet'),
('Skylotec','Inceptor GRX High Voltage Reflective','helmet'),
('Skylotec','Inceptor GRX REF','helmet'),
('Skylotec','Inceptor GRX-MNT','helmet'),
('Skylotec','Inceptor GRX-MNT REF','helmet'),
('Skylotec','BFD Y Band','lanyard'),
('Skylotec','Ergogrip SK12','lanyard'),
('Skylotec','Peanut I','lanyard'),
('Skylotec','Skysafe Eco-R','lanyard'),
('Skylotec','Skysafe Eco-W','lanyard'),
('Skylotec','Skysafe Pro Flex Y','lanyard'),
('Skylotec','Skysafe Pro I','lanyard'),
('Skylotec','Skysafe Pro Tie Back Y','lanyard'),
('Skylotec','Skysafe Pro Y','lanyard'),
('Skylotec','Skysafe Pro+','lanyard'),
('Skylotec','Tuner Pro','lanyard'),
('Skylotec','Veric','lanyard'),
('Skylotec','Claw CL-001','other'),
('Skylotec','Peanut','other'),
('Skylotec','Perisrop Edge Protector','other'),
('Skylotec','Rescue Device Driver RDD','other'),
('Skylotec','Skypack','other'),
('Skylotec','CRIC','pulley'),
('Skylotec','Mini Tandem Pulley','pulley'),
('Skylotec','Orbiter A','pulley'),
('Skylotec','Orbiter D','pulley'),
('Skylotec','Orbiter H','pulley'),
('Skylotec','Loop 26 kN','sling'),
('Skylotec','Rescue Loop','sling'),
('SpanSet','Ergo Harness','harness'),
('SpanSet','Excel-Pro','harness'),
('SpanSet','Pole-Tech','harness'),
('SpanSet','Rig-Tech','harness'),
('SpanSet','Scaff-Pro','harness'),
('SpanSet','X-Harness','harness'),
('SpanSet','Adjustable Rope Lanyard','lanyard'),
('SpanSet','DSL3','lanyard'),
('SpanSet','SP140 Lanyard','lanyard'),
('SpanSet','Spectre S','lanyard'),
('SpanSet','Gotcha Rescue Kit','other'),
('Sterling','Chest Ascender','ascender'),
('Sterling','SafeD Carabiner','carabiner'),
('Sterling','ATS','descender'),
('Sterling','F4 Escape Device','descender'),
('Sterling','FCX Escape Descender','descender'),
('Sterling','Tech Extension Lanyard','lanyard'),
('Sterling','Lightning GT Hook','other'),
('Sterling','Pocket Escape System Bag','other'),
('Sterling','EscapeTech','rope'),
('Sterling','FireTech 2','rope'),
('Sterling','HTP Static','rope'),
('Sterling','SafetyPro','rope'),
('Sterling','SuperStatic 2','rope'),
('Sterling','WorkPro','rope'),
('Sterling','Tech Sewn Sling','sling'),
('Teufelberger','treeMOTION','harness'),
('Teufelberger','treeMOTION S.Light','harness'),
('Teufelberger','antiSHOCK Lanyard','lanyard'),
('Teufelberger','glideHITCH','other'),
('Teufelberger','CE Climb','rope'),
('Teufelberger','KM G','rope'),
('Teufelberger','KM III','rope'),
('Teufelberger','KM III Max','rope'),
('Teufelberger','KM Pro','rope'),
('Teufelberger','Patron','rope'),
('Teufelberger','Patron Plus','rope'),
('Teufelberger','Sirius Bull','rope'),
('Yale Cordage','Aramid Escape Rope','rope'),
('Yale Cordage','Bee-Line','rope'),
('Yale Cordage','Double Esterlon','rope'),
('Yale Cordage','Imori','rope'),
('Yale Cordage','Kernmaster','rope'),
('Yale Cordage','Kernmaster Phantom','rope'),
('Yale Cordage','Kernmaster Safari','rope'),
('Yale Cordage','XTC Fire','rope'),
('Yale Cordage','Yalex','rope')
ON CONFLICT (manufacturer, model) DO UPDATE SET category = EXCLUDED.category;
