// src/screens/TermsOfServiceScreen.tsx
//
// Placeholder screen surfaced from Settings → Terms of service. Same shape
// as PrivacyPolicyScreen — pre-launch boilerplate that needs to be
// replaced with a real legal document before store submission.

import React from 'react';
import { ScrollView, Text } from 'react-native';
import { Screen } from '../primitives';
import { useTheme } from '../theme/ThemeProvider';

export function TermsOfServiceScreen() {
  const { colors, spacing, typography } = useTheme();
  return (
    <Screen padded={false}>
      <ScrollView
        contentContainerStyle={{
          padding: spacing.base,
          paddingBottom: spacing.xxl,
          gap: spacing.md,
        }}
      >
        <Text style={[typography.title1, { color: colors.textPrimary }]}>Terms of service</Text>
        <Text style={[typography.caption, { color: colors.textSecondary }]}>
          Effective date: pending publication
        </Text>

        <Text style={[typography.body, { color: colors.textPrimary }]}>
          Rope Access Logbook is a digital work-experience logbook for
          SPRAT- and IRATA-certified rope access technicians. The app records
          the work entries you create and the supervisor signatures attached
          to them. The accuracy of those records — including the levels,
          hours, descriptions, and supervisor identities — is your
          responsibility.
        </Text>

        <Text style={[typography.body, { color: colors.textPrimary }]}>
          Signatures generated by this app are content-hash attestations.
          They are not cryptographic non-repudiation. Auditors and
          re-certification bodies treat the logbook the same way they treat a
          paper logbook: trust but verify. Tampering with signed entries
          invalidates the integrity check shown in the app.
        </Text>

        <Text style={[typography.body, { color: colors.textPrimary }]}>
          The subscription is $2.99 per month after a 7-day free trial.
          Billing is handled by Apple App Store or Google Play depending on
          your platform. You can cancel any time from your device's
          subscription settings.
        </Text>

        <Text style={[typography.body, { color: colors.textPrimary }]}>
          We provide the app as-is, without warranty. We are not liable for
          re-certification outcomes, lost work history due to device loss
          before a cloud backup, or any decisions a supervisor or auditor
          makes from the data shown in the app.
        </Text>

        <Text style={[typography.caption, { color: colors.textSecondary, marginTop: spacing.md }]}>
          The above is pre-launch boilerplate, not a final legal document.
          The published terms will supersede this text.
        </Text>
      </ScrollView>
    </Screen>
  );
}
